### ISSUE TITLE
Diffing only partially working with real data

### ISSUE THREAD

**Issue by Shidash** [TransparencyToolkit/LookingGlass#42]
Diffing now works if there is just a single item fields doc and the non item fields part that need to be diffed. But if multiple docs on a page need their item fields diffed, the box doesn't show up.

I've sent you an email with details on how to duplicate this on our test data instance. Could you please look into this?

Thanks

**Comment by bnvk** [comment]
@Shidash i've pushed a fix for the issues I had discovered with the live data.

I will still try to import some other test data and see if I can replicate the bugs you described locally or if I find them in the testing server!

**Comment by bnvk** [comment]
@Shidash I figured out what was causing the error (which i'm 99% sure was the error you were describing). It had nothing to do with multiple diffing instances on a page. Which is why I wasn't finding it in any of the multi-diffing pages I looked at.

In profiles like [this one](https://ddct.transparencytoolkit.org/docs/christopher-burch2564a820USAFBallisticMissileandSpaceControlDutyOfficer(SecretClearance)2005-02-01icwatch2_linkedin) the title hash was being used as the unique ID, but it had special characters like `(  )` which work fine for loading the URL, but causes JS to crash as those ID's were being used as DOM selectors- which can't contain parenthesis and other special chars- so this was braking the JS

```
#versions-diff-data-christopher-burch2564a820USAFOrbitalandAtmosphericReentryAnalyst(TS-SCIClearance)2008-07-01icwatch2_linkedin
```

I've pushed a fix with using `.gsub()` to strip out those chars in the view!
